# -----------------------------------------------------
# docker-compose.yml
# PULSE - Monitoring f√ºr Proxmox und Docker,.. 
#                PVE, PBS, PMG - STORAGE, BACKUPS, Docker
# -----------------------------------------------------
services:
  pulse:
    image: rcourtman/pulse:latest
    container_name: pulse
    restart: unless-stopped
    ports:
      - "7655:7655"
    volumes:
      - /opt/pulse/data:/data
      - /opt/pulse/certs:/certs
    environment:
      # First-boot Admin
      PULSE_AUTH_USER: admin             # Username for web UI login
      PULSE_AUTH_PASS: < change Me >     # Password
      
      # - API_TOKENS=token-a,token-b        # Comma-separated tokens (plain or SHA3-256 hashed)
      #API_TOKEN: xxxxxxxxxxxx hier reinkopieren vom Proxmox xxxxxxxxxxxxxxxx
      
      HTTPS_ENABLED=true
      TLS_CERT_FILE=/certs/cert.pem
      TLS_KEY_FILE=/certs/key.pem
